[wokwi]
version = 1
# Exercise
# firmware = "target/riscv32imc-unknown-none-elf/release/blinky"
# elf = "target/riscv32imc-unknown-none-elf/release/blinky"

# Solution
firmware = 'target/riscv32imc-unknown-none-elf/release/hello-world'
elf = 'target/riscv32imc-unknown-none-elf/release/hello-world'
